src/Entity/Articles.php
<?php

namespace App\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use App\Repository\ArticlesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: ArticlesRepository::class)]
/**
 *@Vich\Uploadable
 */
class Articles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, type: 'string')]
    #[Gedmo\Slug(fields: ['id', 'title'])]
    private $slug;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;
    
         /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="article_images", fileNameProperty="imageName")
     * 
     * @var File|null
     */
    private $imageFile;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $imageName;

    #[ORM\Column(type: 'datetime_immutable')]
    private $create_at;

    #[ORM\Column(type: 'datetime_immutable')]
    private $update_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeImmutable $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function setTimestamp() {
        if(!$this->getCreateAt()) {
            $this->setCreateAt(new \DateTimeImmutable());
            $this->setUpdateAt(new \DateTimeImmutable());
        }else {
            $this->setUpdateAt(new \DateTimeImmutable());
        }
    }
}

src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\Articles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content', TextareaType::class);

            $builder->add('imageFile', VichImageType::class, [
                'required' => false,
                'allow_delete' => true,
                'delete_label' => '...',
                'download_label' => '...',
                'download_uri' => true,
                'image_uri' => true,
                // 'imagine_pattern' => '...',
                // 'asset_helper' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ArticlesController extends AbstractController
{
    #[Route('/articles', name: 'app_articles_index', methods: ['GET'])]
    public function index(ArticlesRepository $articlesRepository): Response
    {
        return $this->render('articles/index.html.twig', [
            'articles' => $articlesRepository->findAll(),
        ]);
    }

    #[Route('articles/new', name: 'app_articles_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArticlesRepository $articlesRepository): Response
    {
        $article = new Articles();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articlesRepository->add($article, true);

            return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('articles/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('articles/{slug}', name: 'app_articles_show', methods: ['GET'])]
    public function show(Articles $article): Response
    {
        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('articles/{id}/edit', name: 'app_articles_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Articles $article, ArticlesRepository $articlesRepository): Response
    {
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articlesRepository->add($article, true);

            return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('articles/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('articles/{id}', name: 'app_articles_delete', methods: ['POST'])]
    public function delete(Request $request, Articles $article, ArticlesRepository $articlesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $articlesRepository->remove($article, true);
        }

        return $this->redirectToRoute('app_articles_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;


use App\Repository\ArticlesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ArticlesRepository $articlesRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'articles' => $articlesRepository->findBy([], ['create_at' => 'DESC']),
        ]);
    }

}

templates/articles/_delete_form.html.twig
<form method="post" action="{{ path('app_articles_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/articles/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.title) }}
    {{ form_row(form.content) }}
    
    {{form_row(form.imageFile)}}  
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/articles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Articles{% endblock %}

{% block body %}
<div class="container">
    <a href="{{ path('app_articles_index') }}" class="btn">Retour</a>
        <h1>Modifier un article</h1>

    {{ include('articles/_form.html.twig', {'button_label': 'Update'}) }}

    

    {{ include('articles/_delete_form.html.twig') }}
</div>

{% endblock %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles index{% endblock %}

{% block body %}
    

    <div class="container ">
        <h1>Liste article</h1>
        <a href="{{ path('app_articles_new') }}" class="btn btn-primary mb-4">Créer un article</a>
        <div class="container card">

       <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Contenue</th>
                <th>Image</th>
                <th>Crée a</th>
                <th>Modifier</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.content }}</td>
                <td>{{ article.imageName }}</td>
                <td>{{ article.createAt ? article.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ article.updateAt ? article.updateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_articles_edit', {'id': article.id}) }}" class="btn btn-primary">edit</a>
                    {{ include('articles/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun article trouver</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> 
        </div>
        
    
    </div>
    

    
{% endblock %}

templates/articles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Articles{% endblock %}

{% block body %}
<div class="container">
      <h1 class="mb-4">Crée un article</h1>  
    <a href="{{ path('app_articles_index') }}" class="btn btn-primary mb-4">Retour</a>

    {{ include('articles/_form.html.twig') }}
</div>
  

  
{% endblock %}

templates/articles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SpaceBolg - {{ article.title }}{% endblock %}

{% block body %}
<div class="container">
    <a href="{{ path('app_home') }} " class="btn btn-primary btn-lg mb-5 mt-3 rounded-pill">Retour</a>

    <div class="card mb-3">
        <img src="{{ article.imageName ? vich_uploader_asset(article) }}" class="card-img-top mb-3 " alt="{{ article.title }}">
        <div class="card-body">
            <h2 class="card-title mb-4 text-center fw-bold">{{ article.title }}</h2>
            <p class="card-text">{{ article.content }}</p>
            <p class="card-text"> <small class="text-muted">Publié le {{ article.createAt ? article.createAt|date(' d/m/Y  H:i') : '' }}</small></p>
        </div>
    </div>
  

   
</div>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
    {{ encore_entry_link_tags('app') }}
    {% endblock %}


</head>

<body>
    {% block header %}
    {{include("header.html.twig")}}
    {% endblock %}
    {% block body %}{% endblock %}
    {% block footer %}
    {{include("footer.html.twig")}}
    {% endblock %}

    {% block javascripts %}{{ encore_entry_script_tags('app') }}{% endblock %}
</body>

</html>

templates/footer.html.twig
<footer class="overflow-hidden">
    <div class="row text-center ">
        <div class="col">
    
        </div>
        <div class="col text-center">
            <img src="{{ asset('images/logo_space.png') }}" height="200" class="mb-5 mt-5" width="auto" alt="">
        </div>
        <div class="col">
        
        </div>
      </div>
      
</footer>

templates/header.html.twig
<header>
  <div class="container">
    <nav class="navbar ">
      <a href="/" class="navbar-brand title "><svg xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink" width="60" height="60" viewBox="0 0 60 60">
          <defs>
            <clipPath id="clip-path">
              <rect id="Rectangle_7" data-name="Rectangle 7" width="60" height="60" transform="translate(35 19)"
                fill="#dc5e44" />
            </clipPath>
          </defs>
          <g id="Groupe_de_masques_1" data-name="Groupe de masques 1" transform="translate(-35 -19)"
            clip-path="url(#clip-path)">
            <g id="galaxy-spiral-shape" transform="translate(34.986 79.03)">
              <path id="Tracé_1" data-name="Tracé 1"
                d="M44.307-56.017c-4.5.4-9.952,2.544-15.343,6.037-2.086,1.371-2.356,1.606-2.356,2.168a.965.965,0,0,0,.75,1c.293.07.469-.012,2.45-1.043a12.984,12.984,0,0,1,5.708-1.559c2.192-.105,3.587.293,4.618,1.325s1.336,2.673.961,5.31c-1.02,7-4.771,13.562-10.737,18.8C26.08-20.231,22.283-18.4,18.766-18.4c-3.024-.012-4.771-1.336-5.345-4.067a8.342,8.342,0,0,1-.176-1.418c0-.5-.059-.68-.293-.9-.445-.457-.938-.4-1.489.188-1.067,1.125-1.782,3.352-1.957,6.142l-.082,1.289-.375-.762c-2.368-4.9-1.16-12.624,3.329-21.321a16.092,16.092,0,0,0,.867-1.84,1.08,1.08,0,0,0-1.055-.985c-.457,0-2.3,1.383-3.528,2.661a30.064,30.064,0,0,0-5.322,8.064C.961-26.538.211-24.076.035-20.5A17.032,17.032,0,0,0,3.388-9.237a13.466,13.466,0,0,0,8.088,4.958c5.2,1.078,11.464-.4,18.368-4.337a65.593,65.593,0,0,0,6.67-4.548,48.32,48.32,0,0,0,7.631-7.76,44.348,44.348,0,0,0,8.369-18.415c.363-2.04.328-1.969.656-1.184,2.063,4.888,1.02,12.155-2.837,19.786-.809,1.582-.809,2.016,0,2.333.492.188.973-.105,2.086-1.266,5.029-5.24,8.229-14.582,7.49-21.884-.469-4.548-1.864-7.818-4.56-10.631a11.881,11.881,0,0,0-7.982-3.845A11.611,11.611,0,0,0,44.307-56.017Z"
                fill="#dc5e44" />
              <path id="Tracé_2" data-name="Tracé 2"
                d="M30.417-46.019a17.019,17.019,0,0,0-5.427,2.825,26.93,26.93,0,0,0-4.079,4.325A15.954,15.954,0,0,0,18.7-34.4a7.975,7.975,0,0,0-.012,3.458,3.543,3.543,0,0,0,3.165,2.368l.352.035-.481.328c-1.465,1.008-3.247.832-3.868-.4a5.252,5.252,0,0,1-.434-2.766c.07-.785.059-.856-.223-1.137a.926.926,0,0,0-1.336-.047,10.485,10.485,0,0,0-1.09,3.141,10.75,10.75,0,0,0,.059,3.692,5.5,5.5,0,0,0,2.731,3.6,3.063,3.063,0,0,0,1.957.375,4.882,4.882,0,0,0,2.04-.316c3.493-1.266,6.482-4.22,8.615-8.533,1.125-2.262,1.418-3.282,1.418-4.853,0-1.172-.023-1.348-.316-1.887a3.814,3.814,0,0,0-1.981-1.735,3.581,3.581,0,0,1-.727-.3c-.059-.047.457-.363,1.149-.7,3.024-1.477,4.161-.563,4.161,3.364,0,1.067.023,1.184.27,1.418a1,1,0,0,0,1.219.082,4.673,4.673,0,0,0,.715-1.137c1.782-3.657.949-8.252-1.711-9.553A6.144,6.144,0,0,0,30.417-46.019Z"
                fill="#dc5e44" />
            </g>
          </g>
        </svg> SpaceBlog</a>
      <a href="{{path('app_articles_index')}}" type="button" class="btn btn-primary">
        Admin
      </a>
    </nav>
  </div>
</header>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SpaceBlog - Home{% endblock %}

{% block body %}
<div class="container">

  <div class="card border border-0 bg-dark text-white mb-5">
    <img src="{{ asset('images/cover.png') }}" class="card-img" alt="...">
  </div>
  <div>
    <h1 class="fw-bold title mb-5">Nos Articles</h1>
    
    <div class="row row-cols-1 row-cols-md-3 g-4 mb-5">
      {% for article in articles %}
      <div class="col">
        <div class="card h-100">
          <img src="{{ article.imageName ? vich_uploader_asset(article) }}" class="card-img-top" height="200" width="auto" alt="...">
          <div class="card-body">
            <h5 class="card-title fw-bold">{{ article.title }}</h5>
            <a href="{{ path('app_articles_show', {'slug': article.slug}) }}" class="stretched-link"></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    
  </div> 
</div>


{% endblock %}